### ISSUE TITLE
大佬。。。。你这项目编译起来一堆错误啊。。。。

### ISSUE THREAD

**Issue by zzjfengqing** [sindney/fury3d#1]

**Comment by sindney** [comment]
平台？编译器？错误贴一下我看看？
第三方库都准备好了吗？Rapidjson（1.1.0），SFML（2.4.1）？
有下载FBXSDK吗？需要FBXSDK才能解析fbx，（不用fbx解析的话，可以cmake取消FBXPARSER_IMP选项）

**Comment by zzjfengqing** [comment]
windows平台  VS2015  没下载FBXSDK   刚解决了一下 。现在只剩8个error LNK2019: 无法解析的外部符号”的错误  都跟SFML库有关  我想问下 您用的SFML是什么版本？  还有您用的那个json库 我去下了最新的版本   有一些方法被弃用了  导致编译不过  您最好注明一下用的那个json库的版本。

**Comment by sindney** [comment]
嗯嗯，很久没更新了，我标记一下我用的版本
rapidjson是 1.1.0，sfml 2.4.1

**Comment by zzjfengqing** [comment]
恩 我自己下了SFML的库 自己编译 可以链接上了    不过还剩最后两个错误   我看不出跟什么库有关。。。
大佬帮忙看下。。。

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 _htonl@4，该符号在函数 "public: static bool __cdecl fury::FileUtil::SaveCompressedFile(class std::shared_ptr<class fury::Serializable> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?SaveCompressedFile@FileUtil@fury@@SA_NABV?$shared_ptr@VSerializable@fury@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@H@Z) 中被引用	fury	D:\PrivaSpace\fury3d\fury3d\engine\Build\FileUtil.obj	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 _ntohl@4，该符号在函数 "public: static bool __cdecl fury::FileUtil::LoadCompressedFile(class std::shared_ptr<class fury::Serializable> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadCompressedFile@FileUtil@fury@@SA_NABV?$shared_ptr@VSerializable@fury@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) 中被引用	fury	D:\PrivaSpace\fury3d\fury3d\engine\Build\FileUtil.obj	1

**Comment by sindney** [comment]
SaveCompressedFile 这个函数和LZ4压缩有关，你看看engine/ThridParty里的三个库链接上没
stb_image全头文件没问题，lz4和imgui有cpp，估计是他们的cpp没包含进来，你看看是不是

改天我还是提供下VS13/15的项目设置文件吧，可以避免这些错误，windows上设置有点麻烦

**Comment by zzjfengqing** [comment]
额   是要把那个ThirdParty目录下的文件全部添加进项目吗？  还是只是在include里引用他们目录就好？

**Comment by sindney** [comment]
好像不是lz4问题，_ntohl@4是大小头转换函数
`#if defined(_WIN32)
#include <winsock.h>
#else 
#include <arpa/inet.h>
#endif`
http://www.cplusplus.com/forum/windows/21655/
需要你链接windows自带的ws2_32.lib这个库在项目里

**Comment by zzjfengqing** [comment]
没错，加了ws2_32.lib这个 然后再把lz4的文件添加进项目 就可以编译成功了 ，顺便说一下EnumUtil.h里有个Side的枚举IN和OUT   好像跟某处文件的#Define有冲突 我改了名字 才不报错。

**Comment by sindney** [comment]
嗯嗯 可以在header里 undefine IN OUT，改名也可以，可能是vs2015占用了
我用的VS13 盒 苹果llvm 没有这个问题
没问题就好，demo跑得起来吗

**Comment by zzjfengqing** [comment]
跑是跑起来了。。。不过  就一个黑窗口加一个选择UI   控制台报错了 加载json失败 [EROR][fury::fileutil:loadFle][165]：Path Resource/Pipeline/DefferedLightingLambert.json not found

**Comment by zzjfengqing** [comment]
可以了  我改了调试目录  刚是路径不对  现在Demo可以跑了  弄了一上午 终于可以安心看代码了  谢谢大佬了！

**Comment by sindney** [comment]
不客气
